-- Forms and responses schema for Supabase
create table if not exists public.forms (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  description text,
  schema jsonb not null,
  created_at timestamptz default now()
);

create table if not exists public.responses (
  id bigint generated by default as identity primary key,
  form_id uuid not null references public.forms(id) on delete cascade,
  answers jsonb not null,
  created_at timestamptz default now()
);

-- Enable RLS
alter table public.forms enable row level security;
alter table public.responses enable row level security;

-- Public read of forms and responses for anonymous collection
create policy if not exists "forms_read" on public.forms for select using (true);
create policy if not exists "responses_insert" on public.responses for insert with check (true);
create policy if not exists "responses_read" on public.responses for select using (true);





